[params]
  # Mobile Devtools config
  [params.mDevtools]
    enable = false
    # "eruda", "vConsole" supported
    type = "eruda"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.127.0"
