[params]
  # Mobile Devtools config
  [params.mDevtools]
    enable = false
    # "vConsole", "eruda" supported
    type = "vConsole"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.127.0"
